version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.python
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env
    command: watchmedo auto-restart --debug-force-polling --directory=/app --pattern="*.py" --recursive -- python main.py
    ports:
      - "80:80"
