version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.python
    volumes:
      - ./app:/app
    working_dir: /app
    command: python main.py
    ports:
      - "8080:80"
