FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y \
    libgl1-mesa-glx \
    libegl1-mesa \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libglib2.0-0 \
    tesseract-ocr \
    libtesseract-dev

WORKDIR /app

RUN chmod -R 777 /app

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python", "main.py"]